### ISSUE TITLE
I know that you're aware about the second version being more buggy, but...

### ISSUE THREAD

**Issue by OneGunBullet** [mrzenc/KelvinsBetterPlayerAnimations#2]
Couldn't you have just released it later, when it's more polished? Version 1 is way more polished than version 2, especially with the jump animations deleted which I did. 

I think it'd be better to have version 1 (with the jumping animations deleted) as the main download and version 2 as testing.

**Comment by mrzenc** [comment]
Sorry for the late reply

I don't have much knowledge of Java and Fabric API, so completely rewriting the mod was a bit of a challenge for me. Nevertheless, when I made it, it had a lot of bugs, but I decided to put it on GitHub anyway so I could fix the bugs in future releases

But time went on and I stopped playing Minecraft, got into other things, so this repository is no longer maintained. Maybe someday I'll continue development, but I don't have the effort and motivation to do so now

I also updated the README.md that says to use v1.0 instead for anyone who randomly finds this and wants to play with it, so I can close the issue, I guess?
